AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  API Gateway proxy baseline infrastructure


Resources:
  ApiGateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !Sub "${AWS::StackName}-ApiGW"

Outputs:
  ApiGwLogicalID:
    Description: "API Gateway Logical ID (!Ref)"
    Value: !Ref ApiGateway
  ApiGwLogicalID:
    Description: "API Gateway Logical ID (!Ref)"
    Value: !Ref ApiGateway
  ApiGwRootResourceID:
    Description: "API Gateway RootResourceId (!GetAtt RootResourceId.RootResourceId)"
    Value: !GetAtt ApiGateway.RootResourceId
