AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crud
  
  Sample SAM Template for crud

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  PingPongFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pingpong/
      Handler: pingpong
      Runtime: go1.x
      Tracing: Active
Outputs:
  PingPongFunctionArn:
    Description: "First Lambda Function ARN"
    Value: !GetAtt PingPongFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-PingPongFunctionArn"
  PingPongFunctionRef:
    Description: "First Lambda Function Ref"
    Value: !Ref PingPongFunction
